# Generated by Django 4.1.7 on 2023-04-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carbon_Calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConstantValues',
            new_name='ConstantValuesGram',
        ),
    ]
