# Generated by Django 4.1.7 on 2023-04-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carbon_Calculator', '0002_rename_constantvalues_constantvaluesgram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantValuesPublicTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.FloatField()),
                ('subway', models.FloatField()),
                ('trolleybus', models.FloatField()),
                ('electro_train', models.FloatField()),
                ('diesel_train', models.FloatField()),
                ('coal_train_lokomotiv', models.FloatField()),
                ('petrol_taxi', models.FloatField()),
                ('gas_taxi', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ConstantValuesGram',
            new_name='ConstantValuesHome',
        ),
    ]
